In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [3]:
A = np.random.randn(100)

In [4]:
A

array([-1.14135628e+00, -6.36255040e-01, -5.96140378e-01, -8.08472017e-01,
       -1.64692642e+00, -5.17227428e-01,  4.38368231e-01, -4.66557114e-01,
        8.68279736e-01,  4.37765633e-01,  3.25408089e-01, -8.43492164e-01,
        3.97891251e-01,  1.23966293e+00, -2.11704185e-01,  9.85119809e-02,
        6.72441771e-01,  4.76014863e-01,  5.25733264e-02, -1.04791275e+00,
       -1.00774957e+00,  1.06608165e-01,  6.81281456e-01, -4.66511084e-01,
       -1.78061047e+00, -7.58990924e-01, -6.26284434e-01,  1.87363985e-01,
       -2.67547725e+00,  1.48850878e+00,  1.66852249e-01, -2.59765740e-01,
        5.57921239e-01, -6.16257693e-01,  2.68300588e-01,  3.38660881e-01,
        4.31953858e-01,  1.27421006e+00, -1.97118919e-01,  1.44716819e+00,
        5.10993861e-01, -1.48395175e+00,  1.29028465e+00,  2.55591464e-02,
       -3.78110350e-04, -9.06457559e-02,  8.12641423e-01, -1.99081919e+00,
       -1.69198606e+00, -2.33616727e-01,  4.98041403e-01,  4.48083628e-01,
        3.92997989e-01,  

In [5]:
A = 10*A + 50

In [6]:
A

array([38.5864372 , 43.6374496 , 44.03859622, 41.91527983, 33.53073581,
       44.82772572, 54.38368231, 45.33442886, 58.68279736, 54.37765633,
       53.25408089, 41.56507836, 53.97891251, 62.39662934, 47.88295815,
       50.98511981, 56.72441771, 54.76014863, 50.52573326, 39.52087248,
       39.92250429, 51.06608165, 56.81281456, 45.33488916, 32.19389531,
       42.41009076, 43.73715566, 51.87363985, 23.24522745, 64.8850878 ,
       51.66852249, 47.4023426 , 55.57921239, 43.83742307, 52.68300588,
       53.38660881, 54.31953858, 62.74210064, 48.02881081, 64.47168187,
       55.10993861, 35.16048248, 62.90284652, 50.25559146, 49.9962189 ,
       49.09354244, 58.12641423, 30.09180806, 33.08013935, 47.66383273,
       54.98041403, 54.48083628, 53.92997989, 50.82549139, 66.29064573,
       54.13649344, 36.67947604, 57.8259449 , 44.31779134, 53.94056242,
       40.03071436, 49.83188107, 43.94022781, 51.10495767, 37.81569792,
       37.95793565, 46.41804613, 46.87043429, 37.51185534, 52.04

In [7]:
A.shape

(100,)

In [8]:
A.shape = (5, 20)

In [9]:
A

array([[38.5864372 , 43.6374496 , 44.03859622, 41.91527983, 33.53073581,
        44.82772572, 54.38368231, 45.33442886, 58.68279736, 54.37765633,
        53.25408089, 41.56507836, 53.97891251, 62.39662934, 47.88295815,
        50.98511981, 56.72441771, 54.76014863, 50.52573326, 39.52087248],
       [39.92250429, 51.06608165, 56.81281456, 45.33488916, 32.19389531,
        42.41009076, 43.73715566, 51.87363985, 23.24522745, 64.8850878 ,
        51.66852249, 47.4023426 , 55.57921239, 43.83742307, 52.68300588,
        53.38660881, 54.31953858, 62.74210064, 48.02881081, 64.47168187],
       [55.10993861, 35.16048248, 62.90284652, 50.25559146, 49.9962189 ,
        49.09354244, 58.12641423, 30.09180806, 33.08013935, 47.66383273,
        54.98041403, 54.48083628, 53.92997989, 50.82549139, 66.29064573,
        54.13649344, 36.67947604, 57.8259449 , 44.31779134, 53.94056242],
       [40.03071436, 49.83188107, 43.94022781, 51.10495767, 37.81569792,
        37.95793565, 46.41804613, 46.87043429, 3

In [10]:
A. reshape(100,1)

array([[38.5864372 ],
       [43.6374496 ],
       [44.03859622],
       [41.91527983],
       [33.53073581],
       [44.82772572],
       [54.38368231],
       [45.33442886],
       [58.68279736],
       [54.37765633],
       [53.25408089],
       [41.56507836],
       [53.97891251],
       [62.39662934],
       [47.88295815],
       [50.98511981],
       [56.72441771],
       [54.76014863],
       [50.52573326],
       [39.52087248],
       [39.92250429],
       [51.06608165],
       [56.81281456],
       [45.33488916],
       [32.19389531],
       [42.41009076],
       [43.73715566],
       [51.87363985],
       [23.24522745],
       [64.8850878 ],
       [51.66852249],
       [47.4023426 ],
       [55.57921239],
       [43.83742307],
       [52.68300588],
       [53.38660881],
       [54.31953858],
       [62.74210064],
       [48.02881081],
       [64.47168187],
       [55.10993861],
       [35.16048248],
       [62.90284652],
       [50.25559146],
       [49.9962189 ],
       [49