In [2]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [3]:
grades = np.array([[85, 70, 82],
          [75, 92, 85],
          [66, 67, 64],
          [87, 94, 60]])

In [4]:
grades

array([[85, 70, 82],
       [75, 92, 85],
       [66, 67, 64],
       [87, 94, 60]])

In [6]:
weights = np.array([0.3, 0.4, 0.3])

In [7]:
np.dot(grades, weights)

array([78.1, 84.8, 65.8, 81.7])

In [8]:
L = np.array([3, 5, 7, 9])

In [9]:
L * 3

array([ 9, 15, 21, 27])